package com.pm.socialservice.model;

import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Relationship;
import java.util.UUID;
import java.util.Set;

@Node("User")
public class UserNode {
    @Id
    private UUID userId; // Match the ID generated by user-service

    @Relationship(type = "FRIEND", direction = Relationship.Direction.OUTGOING)
    private Set<UserNode> friends;

    @Relationship(type = "BLOCKED", direction = Relationship.Direction.OUTGOING)
    private Set<UserNode> blocked;

    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public Set<UserNode> getFriends() {
        return friends;
    }

    public void setFriends(Set<UserNode> friends) {
        this.friends = friends;
    }

    public Set<UserNode> getBlocked() {
        return blocked;
    }

    public void setBlocked(Set<UserNode> blocked) {
        this.blocked = blocked;
    }
}