package com.pm.socialservice.model;

import org.springframework.data.neo4j.core.schema.Id;
import org.springframework.data.neo4j.core.schema.Node;
import org.springframework.data.neo4j.core.schema.Relationship;

import java.util.HashSet;
import java.util.UUID;
import java.util.Set;

@Node("User")
public class UserNode {
    @Id
    private UUID userId; // Match the ID generated by user-service

    @Relationship(type = "FRIENDS_WITH", direction = Relationship.Direction.OUTGOING)
    private Set<FriendRelationship> friends;

    @Relationship(type = "REQUESTED_FRIEND", direction = Relationship.Direction.OUTGOING)
    private Set<UserNode> friendRequests;

    @Relationship(type = "BLOCKED", direction = Relationship.Direction.OUTGOING)
    private Set<UserNode> blocked;

    public UserNode(){
        this.friends = new HashSet<>();
        this.friendRequests = new HashSet<>();
        this.blocked = new HashSet<>();
    }

    public UserNode(UUID userId){
        this.userId = userId;
        this.friends = new HashSet<>();
        this.friendRequests = new HashSet<>();
        this.blocked = new HashSet<>();
    }


    public UUID getUserId() {
        return userId;
    }

    public void setUserId(UUID userId) {
        this.userId = userId;
    }

    public Set<FriendRelationship> getFriends() {
        return friends;
    }

    public void setFriends(Set<FriendRelationship> friends) {this.friends = friends;
    }

    public Set<UserNode> getBlocked() {
        return blocked;
    }

    public void setBlocked(Set<UserNode> blocked) {
        this.blocked = blocked;
    }

    public Set<UserNode> getFriendRequests() {
        return friendRequests;
    }

    public void setFriendRequests(Set<UserNode> friendRequests) {
        this.friendRequests = friendRequests;
    }
}